website/shoe2/eCommerce/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Models
{
    public partial class ShoppingCart
    {
        StoreEntities storeDB = new StoreEntities();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        // Sends cookies to clients 
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] = context.User.Identity.Name;
                }
                else
                {
                    // Generate a random GUID 
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to cliend as a cookie
                    context.Session[CartSessionKey] = tempCartId;
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        public void AddToCart(Product Product, int quantity)
        {
            // Get the matching cart and Product instances
            var cartItem = storeDB.Carts.SingleOrDefault(c => c.cartId == ShoppingCartId && c.ProductId == Product.ProductId);

            if (cartItem == null)
            {
                // Create new cart item if no cart item exists
                cartItem = new Cart
                {
                    ProductId = Product.ProductId,
                    cartId = ShoppingCartId,
                    Count = quantity,
                    DateCreated = DateTime.Now
                };
                storeDB.Carts.Add(cartItem);
            }
            else
            {
                // If item already exists in the cart, add one to the quantity
                cartItem.Count += quantity;
            }
            storeDB.SaveChanges();
        }

        /*public void UpdateCart(Product Product, int quantity)
        {
            var cartItem = storeDB.Carts.SingleOrDefault()
        }*/

        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = storeDB.Carts.Single(
                cart => cart.cartId == ShoppingCartId
                && cart.RecordId == id);

            int itemCount = 0;

            if (cartItem != null)
            {                
                 storeDB.Carts.Remove(cartItem);
                // Save changes
                storeDB.SaveChanges();
            }
            return itemCount;
        }
        public void EmptyCart()
        {
            var cartItems = storeDB.Carts.Where(
                cart => cart.cartId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                storeDB.Carts.Remove(cartItem);
            }
            // Save changes
            storeDB.SaveChanges();
        }

        public void UpdateCart(int id, int count)
        {
            var cartItem = storeDB.Carts.Single(
                cart => cart.cartId == ShoppingCartId
                && cart.RecordId == id);

            if (cartItem != null)
            {
                cartItem.Count = count;
            }
            // Save changes 
            storeDB.SaveChanges();
        }
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in storeDB.Carts
                          where cartItems.cartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }
        public decimal GetSubTotal()
        {
            // Multiply Product price by count of that Product to get 
            // the current price for each of those Products in the cart
            // sum all Product price totals to get the cart total
            decimal? total = (from cartItems in storeDB.Carts
                              where cartItems.cartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Product.Price).Sum();

            return total ?? decimal.Zero;
        }
        
        public List<Cart> GetCartItems()
        {
            return storeDB.Carts.Where(c => c.cartId == ShoppingCartId).ToList();
        }
        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
               { 
                    ProductId = item.ProductId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count
                };
                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Product.Price);

                storeDB.OrderDetails.Add(orderDetail);

            }
            // Set the order's total to the orderTotal count
            order.Total = orderTotal;
            // Save the order
            storeDB.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return order.OrderId;
        }
        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = storeDB.Carts.Where(
                c => c.cartId == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.cartId = userName;
            }
            storeDB.SaveChanges();
        }
    }
}

website/shoe2/eCommerce/ViewModels/ShoppingCartViewModel.cs
using eCommerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCommerce.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartSubTotal { get; set; }
    }
}

website/shoe2/eCommerce/Controllers/ShoppingCartController.cs
using eCommerce.Models;
using eCommerce.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Controllers
{
    public class ShoppingCartController : Controller
    {
        StoreEntities storeDB = new StoreEntities();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartSubTotal = cart.GetSubTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5?quantity=XXX
        public ActionResult AddToCart(int id, string quantity)
        {
            int quantityNumber;
            if(!Int32.TryParse(quantity, out quantityNumber))
                quantity = "1";

            if (string.IsNullOrEmpty(quantity))
                quantity = "1";
            // Retrieve the Product from the database
            var addedProduct = storeDB.Products
                .Single(Product => Product.ProductId == id);
 
            quantityNumber = Int32.Parse(quantity);
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedProduct, quantityNumber);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/UpdateCart?title=X&?quantity=Y
        [HttpPost]
        public void UpdateCart(List<cartItem> cartItemsUpdate)
        {
            // Get the Cart 
            var cart = ShoppingCart.GetCart(this.HttpContext);

            foreach (cartItem itemToUpdate in cartItemsUpdate)
            {
                cart.UpdateCart(itemToUpdate.recordId, Int32.Parse(itemToUpdate.quantity));
            }
        }

        public class cartItem
        {
             public int recordId { get; set;}
             public string quantity { get; set;}
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public void RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the Product to display confirmation
            string ProductName = storeDB.Carts
                .Single(item => item.RecordId == id).Product.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message        
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

        //
        // GET: /ShoppingCart/Review
        public ActionResult Review()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartSubTotal = cart.GetSubTotal()
            };
            // Return the view
            return View(viewModel);
        }
               
    }
}

website/shoe2/eCommerce/Controllers/StoreController.cs
using eCommerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Controllers
{
    public class StoreController : Controller
    {
        StoreEntities storeDB = new StoreEntities();
        // GET: Store
         // GET: /Store/
        public ActionResult Index()
        {
            var products = storeDB.Products.ToList();           
            return View(products);
        }
        //
        // GET: /Store/Browse
      public ActionResult Browse(string genre)
        {
            if (!string.IsNullOrEmpty(genre))
            {
                var genreModel = storeDB.Genres.Include("Products").SingleOrDefault(g => g.Name == genre);
                return View(genreModel);
            }
            return RedirectToAction("Index");
        }
        //
        // GET: /Store/Details
      public ActionResult Details(int? id)
         {
            var count = storeDB.Products.Count();
            TempData["count"] = count.ToString();
            var Product = storeDB.Products.Find(id);
            return View(Product);
         }

      //
      // GET: /Store/GenreMenu
      [ChildActionOnly]
      public ActionResult GenreMenu()
      {
          var genres = storeDB.Genres.ToList();
          return PartialView(genres);
          //storeDB.Products.Where(c => (c.Title.Contains("") || c.Genre.Name.Contains(""))).ToList();
      }

      // GET: /Store/GenreMenuDropDown
      [ChildActionOnly]
      public ActionResult GenreMenuDropDown()
      {
          var genres = storeDB.Genres.ToList();
          return PartialView(genres);
      }

      public ActionResult Search(string SearchText)
      {
          if (!string.IsNullOrEmpty(SearchText))
          {
            var Products = storeDB.Products.Where(c => (c.Title.Contains(SearchText) || c.Genre.Name.Contains(SearchText))).ToList();
            return View(Products);
          }
          return View();
      }
    }
}

website/shoe2/eCommerce/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Cart(" + ViewData["CartCount"] + ")","Index","ShoppingCart",new { id = "cart-status" })

<style type="text/css">
    #cart-status{}
</style>

website/shoe2/eCommerce/Views/ShoppingCart/Index.cshtml
@model eCommerce.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}
<script src="~/Scripts/jquery-1.10.2.min.js"
        type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post                
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete }, function () {
                    window.location.assign('/ShoppingCart/Index');
                });;
            }
        });

        $('tr').each(function (index) {
            if (index % 2 == 0) {
                $(this).css('background-color: #c2d6d6');
            }
        })
        $('#update').click(function () {
            var cartItemsUpdate = [];
            $("table tr:not(:first)").each(function () {
                var prodTitle = $(this).find(".item-count input").attr("data-id");
                var prodQuantity = $(this).find(".item-count input").val();
                cartItemsUpdate.push({ recordId: prodTitle, quantity: prodQuantity });

            });
            things = JSON.stringify({ 'cartItemsUpdate': cartItemsUpdate });

                $.ajax({
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json',
                    type: 'POST',
                    url: '/ShoppingCart/UpdateCart',
                    data: things,
                    success: function () {},
                    failure: function () {}
                });
                window.location.assign('/ShoppingCart/Index');
            })
    });
</script>
<section class="main_content">
    <h3>
      <em id="your_cart">Your Cart</em> 
    </h3>
     <div id="update-message">
    </div>
   <table class="table">
    <tr class="top_table_row">
        <th class="top_row">            
        </th>
        <th>
        </th>
        <th id="price">
            Price
        </th>
        <th id="quantity">
            Quantity
        </th>
        <th id="total">
            Total
        </th>
        <th id="remove">            
        </th>
    </tr>
    @foreach (var item in Model.CartItems)
    {
        <tr class="row" >
            <td id="prod_img">
                <img id="product_img" src=@Url.Content(@item.Product.ProductArtUrl) />
            </td>
            <td class="description">
                @Html.ActionLink(item.Product.Title, "Details", "Store", new { id = item.ProductId }, null)
            </td>
            <td id="item_price">
                $@item.Product.Price
            </td>
            <td class="item-count">
                <input type="text" id="item-count" data-id="@item.RecordId" value="@item.Count.ToString()" />               
            </td>
            <td id="total_price">
                $@(item.Product.Price * item.Count)
            </td>
            <td id="remove">
                <a href="#" class="RemoveLink" data-id="@item.RecordId"> X </a>
            </td>
        </tr>
    }
    </table>
    <div class="subtotal">
        Subtotal  $@Model.CartSubTotal
    </div> 

    <p class="checkout">
        @Html.ActionLink("Review", "Review", "ShoppingCart")
    </p>  
    <div id="continue_shopping">
        @Html.ActionLink("Continue Shopping", "Index", "Store")
    </div>
    <div id="update">UPDATE CART</div>

</section>
<style type="text/css">
    #update{ cursor:pointer; font-family: Georgia, Times, "Times New Roman", serif;  margin-top: 6%; float: right; padding-right: 6%; padding-top: -8%; margin-top: 0%; border: solid 1px #cccccc; background-color: #a1a178;  padding: 12px 6px 9px 8px;}
    #remove{padding-left: 4%;}
    .RemoveLink{text-decoration: none; font-family: cursive; font-size: larger; color: black;}
    #item-count{ width: 16%; margin-left: 29%;}
    .description{padding-left: 5%; padding-right: 14%;}
    #product_img{padding-right: 100px}
    .main_content{padding-left: 9%; padding-bottom: 9%; padding-top: 5%; padding-right:7%;}
    .table{width: 94%; border: solid 1px #c2d6d6;border-collapse: collapse;}
    .top_table_row{    background-color: #c2d6d6;font-family: Georgia, Times, "Times New Roman", serif;}
    .top_row{padding-bottom: 53px;}
    #total{padding-right: 2%;}
    #prod_img{ width: 17%;}
    #product_img{ max-width: 76%;   max-height: 94%;}
    #item_price{    padding-left: 1%;font-family: Georgia, Times, "Times New Roman", serif;}
    .item-count{padding-left: 2%;    font-family: Georgia, Times, "Times New Roman", serif;}
    #total_price{padding-left: 1%;font-family: Georgia, Times, "Times New Roman", serif;}
    #continue_shopping a{    text-decoration: none;
    font-weight: bolder;
    font-size: larger;
    font-family: Georgia, Times, "Times New Roman", serif;
    color: black;
    padding-top: 20px;
    padding-right: 14px;
    padding-bottom: 18px;
    padding-left: 13px;
    border: solid 1px;
    color: white;
    background-color: #86592d;}
    .subtotal{ padding-bottom: 29px; padding-top: 18px; margin-left: 89%; width: 140px;  float: right; margin-right: 6%; font-family: Georgia, Times, "Times New Roman", serif; font-size: larger;}
    .checkout{float: right;
    margin-right: 6%;
    font-family: Georgia, Times, "Times New Roman", serif;
    font-size: larger;}
    .checkout a{
        text-decoration: none;
    color: black;
    padding: 14% 18% 14% 17%;
    border: solid 1px #cccccc;
    background-color: #cccccc;margin-left: 14%;
    }
    .description a{text-decoration: none;
    font-family: Georgia, Times, "Times New Roman", serif;
    color: black;}
    .subtotal{    padding-bottom: 17px;
    margin-right: 6%;
    margin-left: 84%;}
    #your_cart{ font-stretch: semi-condensed; font-family: sans-serif; text-transform: uppercase; font-size: large;}
</style>

website/shoe2/eCommerce/Views/ShoppingCart/Review.cshtml
@model eCommerce.ViewModels.ShoppingCartViewModel

@{
    ViewBag.Title = "Review";
}

<h2>Review Your Order</h2>

<section>
  <table class="items">
  @foreach (var item in Model.CartItems)
  {
    <tr class="row">
        <td id="count">
            @item.Count
        </td>
        <td id="prod_img">
            <img id="product_img" src=@Url.Content(@item.Product.ProductArtUrl) />
        </td>
        <td class="description">
            @Html.ActionLink(item.Product.Title, "Details", "Store", new { id = item.ProductId }, null)
        </td>
         <td id="total_price">
            $@(item.Product.Price * item.Count)
        </td>       
    </tr>
  }
  </table>
  <hr id="first_line">
  <table class="sub_ship">
    <tr id="subttoal">
        <td class="subtotal"> Subtotal </td>
        <td id="subtotal_amnt"> $@Model.CartSubTotal</td>
    </tr>
    <tr id="shipping">
        <td class="shipping">Shipping</td>
        <td id="shipping_amnt"> - </td>
    </tr>
  </table>
  <hr id="second_line">
  <table class="total">
    <tr >
        <td id="total">Total</td>
        <td id="total_amnt">$@Model.CartSubTotal</td>
    </tr>
  </table>
    <div class="continue"><a href="/Checkout/AddressAndPayment"> Place Order </a></div>
</section>

<style type="text/css">
    section{    padding-bottom: 10%;
    padding-right: 44%;    padding-left: 7%;}
    #prod_img{ height: 78px;width:19%}
    h2 { padding-bottom: 3%; padding-top: 2%; padding-left: 2%; font-family: sans-serif; font-style: italic;}
    #product_img{ width: 84%;}
    .description a { text-decoration: none; color: black;font-family: Georgia, Times, "Times New Roman", serif}
    #second_line{ width: 42.5%; margin-left: 11%;}
    .sub_ship{width:100%}
    #subttoal{padding-left:4%}
    #second_line{  margin-left: 0%; width: 100%;}
    #subtotal_amnt{    float: right;
    font-family: Georgia, Times, "Times New Roman", serif;}
    #shipping_amnt{float: right;}
    #total_amnt{ float:right;padding-left: 65%;font-family: Georgia, Times, "Times New Roman", serif}
    section{ padding-bottom: 10%;}
    .total{ width: 100%;}
    #total{padding-right:17%;font-family: Georgia, Times, "Times New Roman", serif}
    .subtotal{font-family: Georgia, Times, "Times New Roman", serif}
    .shipping{padding-top:2%; font-family: Georgia, Times, "Times New Roman", serif}
    #total_price{    font-family: Georgia, Times, "Times New Roman", serif;
    float: right;
    padding-top: 12%;}
    .continue a{  float: right; border: solid 1px #a3a3c2; margin-top: 4%; padding: 1% 2% 1% 2%; text-decoration: none; color: black; font-family: Georgia, Times, "Times New Roman", serif;
    background-color: #a3a3c2;}

</style>